application:
  forwarder:
    endpoint-map-config:
      - key: "/"
        value: "http://116.103.227.208:8080/"
        mode: forward
        priority: 2

#      - key: "/"
#        value: "http://116.103.227.208:8080/"
#        mode: forward
#        load-balancer: "round-robin"
#        stick-mode: "ip"
#        priority: 2
    verbose: true
    connection-timeout: 5000
    read-timeout: 10000
    proxy:
      use-proxy: false
      host: 10.61.11.42
      port: 3128
    header:
      inject-cookie-agent: true
  redis:
    enabled: false
    time-to-live: 3600


spring:
  redis:
    host: localhost
    port: 6379
    password: your_password_here
    timeout: 60000
server:
  port: 8089