application:
  forwarder:
    endpoint-map-config:
      - key: "/rest/docIn/getInfoToDelivery2"
        value: >
          return {'abc': 123}
        mode: eval
        method: "GET, POST"
        priority: 1

      - key: "/api/DmThongbao/SendSMSCDDH"
        value: "D:\\Temp\\ok.json"
        method: "GET, POST"
        mode: mock
        priority: 1

#      - key: "/rest/userSupport/list"
#        value: ""
#
#      - key: "/rest/userSupport/detail"
#        value: ""

      - key: "/voffice"
        value: "http://localhost:8082/voffice"
        method: "GET, POST"
        mode: forward
        rewrite-cookie-path: true
        priority: 2

#      - key: "/"
#        value: >
#          http://116.103.227.208:8080/
#          http://116.103.227.208:8081/
#          http://116.103.227.208:8082/
#        mode: forward
#        load-balancer: "round-robin"
#        stick-mode: "ip"
#        priority: 2
    verbose:
      active: true
      verbose-request-curl: true #Print request as Curl for easy Postman import
      verbose-response-only: true
    connection-timeout: 5000
    read-timeout: 10000
    proxy:
      use-proxy: false
      host: 10.61.11.42
      port: 3128
    header:
      inject-cookie-agent: true
  redis:
    enabled: false
    time-to-live: 3600


spring:
  redis:
    host: localhost
    port: 6379
    password: your_password_here
    timeout: 60000
server:
  port: 8089