application:
  forwarder:
    endpoint-map-config:
      - key: "/rest/docIn/getInfoToDelivery2"
        value: >
          return {'abc': 123}
        mode: eval
        method: "GET, POST"
        priority: 1
#
#      - key: "/rest/invitationOut/actions"
#        value: "/home/mockFile/invitation_out_actions.json"
#        method: "GET, POST"
#        mode: mock
#        priority: 1
#
#      - key: "/rest/mission/actions"
#        value: "/home/mockFile/mission_actions.json"
#        method: "GET, POST"
#        mode: mock
#        priority: 1
#
#      - key: "/rest/workProfileManage/actions"
#        value: "/home/mockFile/work_profile_manager_actions.json"
#        method: "GET, POST"
#        mode: mock
#        priority: 1
#
#      - key: "/rest/docSubmit/actions"
#        value: "/home/mockFile/docSubmit_actions.json"
#        method: "GET, POST"
#        mode: mock
#        priority: 1
#
#      - key: "/rest/count/countInHome"
#        value: "/home/mockFile/count_in_home.json"
#        method: "GET, POST"
#        mode: mock
#        priority: 1

      - key: "/"
        value: "http://localhost:8080/voffice/"
        method: "GET, POST"
        mode: forward
        priority: 2
#      - key: "/"
#        value: "http://116.103.227.208:8080/"
#        mode: forward
#        load-balancer: "round-robin"
#        stick-mode: "ip"
#        priority: 2
    verbose: true
    connection-timeout: 5000
    read-timeout: 10000
    proxy:
      use-proxy: false
      host: 10.61.11.42
      port: 3128
    header:
      inject-cookie-agent: true
  redis:
    enabled: false
    time-to-live: 3600


spring:
  redis:
    host: localhost
    port: 6379
    password: your_password_here
    timeout: 60000
server:
  port: 8089